### ISSUE TITLE
[RAM] Rule Table updates

### ISSUE THREAD

**Issue by mdefazio** [elastic/design-system-team#141]
# Rule Table updates for Stack Management
Target: 8.3 / 8.4

## Summary
Provide an updated view for the Rules table based on recent feedback, new statuses and forthcoming schedule snooze feature.

### Update statuses:
Based on [this RFC](https://docs.google.com/document/d/1-tMHRS3liqhHf8YGVqR93rZg3zdoDe2nEfptkOw1Q-E/edit), we need to show the rule table with these new statuses. 
Previously `Last response`, this will now be `Status` with the following options:

|   |   |
| :--- | :--- | 
| `Succeeded` | Rule executed as expected. Does not necessary indicate that alerts were generated | 
| `Warning` | Rule ran and completed, but with warnings | 
| `Failed` | Rule was not able to execute |

### Update filtering options
Since we have consolidated our statues, we should also update and improve how we filter this table. We want to have the rule statuses easily exposed and clickable to quickly add filters to help searching across a likely large number of rules.
- Expose status filters
- Provide a `View` dropdown filter that provides views for _Enabled_, _Disabled_, _Snoozed_

### Move snoozing to own column
Due to feedback as well as the need to accommodate scheduled snoozing, we will move the snoozing option out of the previous Enabled/Disabled/Snooze badge

**Snoozing updates:** 
Schedule snoozing interactions broken down in separate issue.

[#126601](https://github.com/elastic/kibana/issues/126601)

- - - 

### Links

[Figma mockups](https://www.figma.com/file/bZzJEnSEDTvUYptdnDszZ3/Rules%3A-8.3)

**Issues:**
- [ ] https://github.com/elastic/stack-design-team/issues/140
- [x] https://github.com/elastic/kibana/issues/126601
- [x] #142
- [x] #143

- - - 

## Page states
_Account for all possible views that this page can show_

**EUI component notes:**

Status filters shown using [`EuiFacetGroup`](https://elastic.github.io/eui/#/navigation/facet#facet-layout) in a horizontal grouping.  Mockup shows adding filter selection to search bar.  
 

### Full view

![image](https://user-images.githubusercontent.com/3756330/166949809-6d45f393-2e19-4943-8b2d-579801e68428.png)

### With `Status` filter(s)
<details>
  <summary>View mockups</summary>  
 
--
  
**Single status filter:**

  ![image](https://user-images.githubusercontent.com/3756330/166947624-4406f50e-785d-4f88-88ac-096aa9a6af81.png)

**Multiple status filters**

![image](https://user-images.githubusercontent.com/3756330/166947729-42f98bad-519d-499b-bd66-82676c695a70.png)

</details>

### With a `View` filter
<details>
  <summary>View mockups</summary>  

 --

  ![image](https://user-images.githubusercontent.com/3756330/166951309-a315ae16-9c51-4e75-9fe4-74347145d652.png)

</details>

### Row actions
<details>
  <summary>View mockups</summary>  
 
--

**Rule is enabled**

  ![image](https://user-images.githubusercontent.com/3756330/166954311-944187ae-6956-4cee-9244-55d0807c2ad6.png)

**Rule is disabled** (No snoozing option)

![image](https://user-images.githubusercontent.com/3756330/166954381-43fc6c27-3a60-4d43-a61d-0b671fb7e6d6.png)

</details>

- - -

## Discussions
_Any related discussions will be added here_

**Comment by XavierM** [comment]
I am wondering if it will be a good idea to have an easy way to clear all the filter.

**Comment by mdefazio** [comment]
> I am wondering if it will be a good idea to have an easy way to clear all the filter.

@XavierM 

In the mockups, I am showing the filters being added to the search bar.  I know we discussed this in regards to the KQL implementation, but having a clear button in the search bar is typically how we do this (with [in memory tables](https://elastic.github.io/eui/#/tabular-content/in-memory-tables)).

We can also include a 'Clear all' option on the filter dropdowns to clear that group individually.  

This shows both examples:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/3756330/166965747-38091a9e-5b43-49c7-8aef-a671bb9bbc5d.png">

There are only 3 status filters below the search bar.  So I'm not sure its a huge effort to go and reset those individually.  But I absolutely agree as it pertains to all the filters.  I'm happy to iterate on a solution for the meantime if we don't can't add the filters to the search bar.  But I suppose I'm wondering if an additional clear option would be necessary once we do have the filters showing in the search bar.
